spring.application.name=Tg_bot 
server.port=8081
telegram.bot.token=s
telegram.bot.username=@S
logging.level.root=info
logging.level.org.springframework.web=info

auth.service.url=http://localhost:8081
steam.service.url=http://localhost:8082
