spring.application.name=Tg_bot 
server.port=8081
telegram.bot.token=8385657831:AAF7RduERpmfdX54TlslximvkXlTL9Vd1cs
telegram.bot.username=@SteamAnalitic_bot
logging.level.root=info
logging.level.org.springframework.web=info

auth.service.url=http://localhost:8081
steam.service.url=http://localhost:8082