spring.application.name=Tg_bot
server.port=8081
telegram.bot.token=${TG_BOT_TOKEN}
telegram.bot.username=${TG_BOT_NAME}
logging.level=${LOGGING_LEVEL}
logging.level.org.springframework.web=${LOGGING_LEVEL}

auth.service.url=${AUTH_SERVICE_URL}
steam.stats.service.url=${STEAM_SERVICE_URL}
ai.stats.service.url=${AI_SERVICE_URL}